export const ON_FETCHING_SINISTERS = 'ON_FETCHING_SINISTERS'
export const SUCCESS_GET_SINISTERS = 'SUCCESS_GET_SINISTERS'
export const ERROR_GET_SINISTERS = 'ERROR_GET_SINISTERS'
export const SET_CURRENT_SINISTER = 'SET_CURRENT_SINISTER'
